name: InstantInventory
version: '${project.version}'
main: net.daechler.instantinventory.InstantInventory
api-version: '1.20'
authors: [Daechler]
description: Transfers broken blocks directly to the player's inventory.
